# Generated by Django 6.0.3 on 2026-03-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conteudo_resposta', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.atividade')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aluno', 'atividade')},
            },
        ),
    ]
