# Generated by Django 6.0.3 on 2026-03-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_resposta_feedback_correcao'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
