from .usuario import UsuarioViewSet
from .turma import TurmaViewSet
from .aluno_turma import AlunoTurmaViewSet
from .atividade import AtividadeViewSet
from .me import MeAtividadesView
from .resposta import RespostaViewSet
from .correcao import CorrecaoViewSet
from .me import MeCorrecaoDetailView
from .me import MeCorrecoesView
from .menu import MenuView